- build-apps.js
- package.json
* Sets iLib basepath top an absolute value to prevent copying for each individual ui test app.
* Separate iLib locale data copying into its own step in build process.
Enact-DCO-1.0-Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>
> PLAT-99378: Update iLibWebpackPlugin to support ui/screenshot test structure

- package.json
- webpack.config.js
Update the webpack config and dependencies to use the newer PostCSS Plugin
Signed-off-by: Ryan Duffy <ryan.duffy@lge.com>
> PLAT-98768: Replace less plugin with PostCSS plugin

- build-apps.js
If the ilib files existed in the `dist` directory, testing would abort during build.
This fix checks for the existence first before attempting to make the directory and then will overwrite existing files.
> PLAT-100080 Allow overwriting existing ilib files

- screenshot/utils/confHelpers.js
- utils/generateTestData.js
This PR shortens strings and arrays.  It replaces the excess with an ellipsis.  This will mean that some old filenames won't match up anymore.  With this, we don't have to use substitutions to avoid long filenames.  The text limit is pretty short but this could be adjusted.
> Shorten filenames for long text and arrays

- screenshot/utils/confHelpers.js
- utils/generateTestData.js
If a component has long enough props, it can produce a filename that is too long for the target filesystem. This PR truncates the name to 128 characters to give some context and then appends an md5 hash of the full file name to maintain uniqueness. It also changes the ellipsis character from #81 to three dots because the ellipsis was breaking the newFiles browser. This probably could have been fixed differently but the above hashing obviates the need to use only 1 character for the ellipsis.
Signed-off-by: Ryan Duffy <ryan.duffy@lge.com>
> PLAT-101901: Hash and truncate screenshot file names

- screenshot/utils/redist/failedTests.js
- screenshot/utils/redist/newFiles.js
- utils/generateTestData.js
Some images weren't loading because the src URI wasn't encoded properly.  This, coincidentally, fixes the elipses issue as well, so I reverted that back.
> Fix encoding for image src

- utils/Page.js
- utils/generateTestData.js
New designs transition for spotlight focus.  This will filter out those transitions since we're generally not interested in them.  Sadly, we hardly use this feature anymore.
> Filter transition events that are not relevant

- screenshot/utils/confHelpers.js
- utils/runTest.js
An earlier attempt to fix filenames so they didn't have invalid characters in them caused intended directories to disappear.  This puts screenshots back into subdirectories and applies Windows-safe transforms to all the filenames so that Windows users can view files from the automation server (I'm looking at you, Jason and Jeremy).
A side effect of the problem was directory names were counting as part of the filename length, so filenames were truncated very short, not showing as many of the props as they could.
After this merge, all reference screenshots will need to be retaken since they filenames will be different.
> Put screenshots back in subdirectories

- screenshot/wdio.tv.conf.js
- ui/wdio.tv.conf.js
Enact-DCO-1.0-Signed-off-by: Jeonghee Ahn <jeonghee27.ahn@lge.com>
ui-test is not currently performed on the TV board.
There was a missed part in the wdio.tv.config.js file at https://github.com/enactjs/ui-test-utils/pull/77.
I revive that missed part so that the ui-test could be performed on the TV.
> PLAT-110982: Support ui-test on TV

- config/wdio.conf.js
This prevents the default selenium-standalone from attempting to use Chrome 83 allows us to resume Chrome 79 usage.
Cherrypicked from https://github.com/enactjs/ui-test-utils/pull/93
Enact-DCO-1.0-Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>
> Force specific chromedriver

- src/build-apps.js
* Ensure no ilibmanifest.json files are incidentally generated during ui test building.
* Target test view directories for iLib context to transfer/handle any test-based iLib resbundles.
Enact-DCO-1.0-Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>
> PLAT-115838: i18n ui tests fail with ui-test-utils 0.5.0

- utils/generateTestData.js
With the new build the imported image filenames varied slightly from before.  This will trim off the full path, making the image names more useful.
> PLAT-116194 Remove app name from imported images

- package.json
Update dependencies for React 17.
Enact-DCO-1.0-Signed-off-by: Jeonghee Ahn <jeonghee27.ahn@lge.com>
> PLAT-126474: Update dependent modules for ui-test-utils

- screenshot/wdio.tv.conf.js
- ui/wdio.tv.conf.js
* Issue Resolved : 
We cannot perform the screenshot test on webOS board due to below error.
```
Error: unknown error: unhandled inspector error: {"code":-32601,"message":"'Browser.getWindowForTarget' wasn't found"}
(Session info: content shell=)
```
* Resolution : 
1. We need `remote: true` option like ui-test tv config
2. We should not change viewport size on board env. The option is supported for desktop only. (https://webdriver.io/docs/wdio-novus-visual-regression-service/#options)
Please refer https://github.com/enactjs/ui-test-utils/blob/master/screenshot/wdio.conf.js#L12.
and https://github.com/enactjs/ui-test-utils/blob/master/screenshot/wdio.docker.conf.js#L5
Enact-DCO-1.0-Signed-off-by: Jeonghee Ahn (jeonghee27.ahn@lge.com)
> WRN-793: Support WebOS TV screenshot test

- ui/wdio.docker.conf.js
ui-test-docker runs using 'selenium-standalone', not docker environment.
Remove 'selenium-standalone' service properly. 
screenshot/wdio.docker.conf.js was fixed on https://github.com/enactjs/ui-test-utils/pull/93
WRN-794
Enact-DCO-1.0-Signed-off-by: Jeonghee Ahn (jeonghee27.ahn@lge.com)
> WRN-794: fix worng condition on ui-docker config

- config/wdio.conf.js
- package.json
- utils/Page.js
- utils/runTest.js
- utils/selector.js
@wdio/sync was depreacted on node 16.
Remove @wdio/sync and apply async/await 
Please refer to WDIO page for each API (https://webdriver.io/docs/api/browser/url/ )
Add "body.waitForExist" to resolve screenshot test timing issue.
There was wrong window size, So I fixed it also.
WRN-14979
Enact-DCO-1.0-Signed-off-by: Jeonghee Ahn (jeonghee27.ahn@lge.com)
> WRN-14979: Remove @wdio/sync

- config/wdio.conf.js
Google Chrome installation folder changed from Program files(x86) to Program Files.
If the local chrome version is not read, then ui-test-utils would download the latest release of chromedriver, which can be different than the local version of Chrome. In that case, the ui and ss tests would fail locally
WRN-18565
Enact-DCO-1.0-Signed-off-by: Daniel Stoian [daniel.stoian@lgepartner.com](mailto:daniel.stoian@lgepartner.com)
> WRN-18565: Updated chrome installation folder for Windows

- package.json
- ui/wdio.docker.conf.js
`babel-eslint` has been deprecated
```
`babel-eslint` is now `@babel/eslint-parser`. This package will no longer receive updates.
```
Remove deprecated `babel-eslint` 
WRN-12124
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong (taeyoung.hong@lge.com)
> WRN-12124: Remove deprecated babel-eslint module

- .travis.yml
- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
In current, the latest node version is 18, and the LTS version is 16(includes npm 8).
But we still use `lockfileVersion` 1 in npm-shrinkwrap.json created from npm 6.
For Node 16(LTS) or 18(Current) users, to prevent malfunctions of version asynchronous, need to update the version of the npm-shrinkwrap file to 2.
Update `lockfileVersion` of npm-shrinkwrap.json to v2
WRO-3879
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong …
> WRO-3879: Update the version of npm-shrinkwrap file to v2

- CHANGELOG.md
- utils/Page.js
- UI Tests which were calling waitTransitioEnd were failing randomly, but quite often, with the error `Error: waitUntil condition timed out after 10000ms`
- I added async-await to browser.execute(). It returns a promise and we need to wait for it to be resolved
- the method browser.waitUntil was not called correctly, the timeout and timeout message should have been put in an object, according to https://webdriver.io/docs/api/browser/waitUntil/ . I updated the call of the method accordingly
[//]: # (Were any …
> WRO-11781: Fixed waitTransitionEnd util function

- .travis.yml
Node 19 is now published(https://nodejs.org/en/blog/announcements/v19-release-announce/)
After this change, travis failure occurred continually so we need to block the current node temporarily.
Update .travis.yml to use node 18
WRO-14562
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong taeyoung.hong@lge.com
> WRO-14562: Update .travis.yml to use the node 18

- CHANGELOG.md
- utils/Page.js
- UI Tests which were calling waitTransitioEnd were failing randomly, with a low frequency, with the error `timed out waiting for transitionend`
- I added async-await to browser.execute(). It returns a promise and we need to wait for it to be resolved
- I added await  for callback()
- Check the user story for ui-tests results
- I am not sure if all these changes are necesary. Testing their efficiency is very time consuming considering the very low frequency of the …
> WRO-13695: Fixed waitTransitionEnd util function

- .travis.yml
Need to revert what was built with node 18 because of an canvas module's error when running to the current node version.
Update .travis.yml to build with the current node version again because node 19 support in canvas 2.10.2 library was provided
WRP-9221
Enact-DCO-1.0-Signed-off-by: SJ RO (sj.ro@lge.com)
> WRP-9221: Update .travis.yml to build with the current node version

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
Updated fs-extra dependency from version ^10.1.0 to v. ^11.1.1
fs-extra dependency in ui-test-utils now uses the latest version, ^11.1.1.
The listed breaking changes do not affect enact apps
https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md
There are now breaking changes affecting enact.
Minimum supported Node.js version is now 14.14.0.
WRP-7679
Enact-DCO-1.0-Signed-off-by: Andrei Tirla …
> WRP-7679: Upgrade fs-extra dependency to latest version in ui-test-utils

- npm-shrinkwrap.json
- package.json
Updated dependencies to fix security vulnerabilities
Updated dependencies to fix security vulnerabilities
There were no breaking changes affecting this repo
WRQ-8581
Enact-DCO-1.0-Signed-off-by: Daniel Stoian (daniel.stoian@lgepartner.com)
> WRQ-8581: Updated dependencies to fix vulnerabilties

- .travis.yml
- config/wdio.conf.js
We created a server for Chrome version 120, and an issue occurred where Chrome driver 120 version was not found when building on a server where Chrome version 120 was applied
We can set args in selenium-standalone service. Update the driver import path as it has changed since Chrome version 114
refer to : 
- https://chromedriver.storage.googleapis.com/LATEST_RELEASE
- https://developer.chrome.com/docs/chromedriver/downloads/version-selection
[//]: # (Related issues, …
> WRQ-27998: Updated so that driver path can be found in Chrome 114 or higher

- .travis.yml
- README.md
Updated ReadMe guide
Updated examples for components and themes to be ones available in Sandstone.
Updated the `serve` port to be 3000 because that is the default now.
Updated the view screenshots URL to be for `Sandstone-View`.
Removed `--pack-tests` example as it is no longer in the code and no longer works.
Changed Travis dist to `jammy` so that the Travis jobs would pass.
WRR-4294
Enact-DCO-1.0-Signed-off-by: Paul Beldean …
> WRR-4294: Updated ReadMe guide examples to reference Sandstone and removed any Moonstone references

- CHANGELOG.md
- README.md
- src/build-apps.js
In this PR https://github.com/enactjs/sandstone/pull/1769, I added conditions to turn off animation and shadow effects with cli `--no-animation` build option.
To verify effects are removed with that option, we need screenshot test for `--no-animaton`. 
I added `--no-animation` option for test.
`npm run test-ss -- --no-animation` will pack the app with no effects and run the screenshot test.
`--no-animation` option can be used not only for sandstone screenshot test …
> WRR-1039: Added `--no animation` option for screenshot test

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- screenshot/utils/confHelpers.js
- screenshot/wdio.conf.js
- utils/runTest.js
Replaced deprecated `image-comparison-service` with `@wdio/visual-service`
`waitforfontsloaded` parameter was added in order to take screenshots only after all fonts were loaded. https://webdriver.io/docs/visual-testing/method-options/#waitforfontsloaded
WRR-13694
Enact-DCO-1.0-Signed-off-by: Ion Andrusciac ion.andrusciac@lgepartner.com
> WRR-13694: Replaced deprecated `image-comparison-service`

- CHANGELOG.md
- config/wdio.conf.js
- screenshot/wdio.tv.conf.js
- ui/wdio.conf.js
- ui/wdio.tv.conf.js
Error shots were not saved  correctly after an ui-test fail
Ss-tests on TV board are not compared with the correct reference and they fail.
Added `await` to `browser.saveScreenshot()`., according to wdio documentation https://webdriver.io/docs/api/element/saveScreenshot/ 
On TV board, only 1 instance should be run at one moment. I noticed that 5 instances were run in paralel and this caused incorrect screenshot comparison.
Replaced maxInstances with `wdio:maxInstances`. The config property name changed in wdio9. We missed this during the migration
wdio7: https://v7.webdriver.io/docs/options/#capabilities-1 …
> WRR-22655: fix for ss-tests on TV board and Fix for ui test screenshot saving error

- npm-shrinkwrap.json
- package.json
- screenshot/TestChooser.js
https://ko.react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-deprecated-react-apis
PropTypes were deprecated in April 2017 (v15.5.0).
However, the enact/prop-types rule still exists, so removing PropType causes a linting error.
Remove unused eslint-disable directive 'enact/prop-types'
WRR-23385
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong (taeyoung.hong@lge.com)
> WRR-23385: Remove unused eslint-disable directive 'enact/prop-types'
